### ISSUE TITLE
第四章中 NestedMonitorLockoutExample 这个保护性暂挂的例子有点问题11

### ISSUE THREAD

**Issue by Jakye** [Viscent/JavaConcurrencyPattern#2]
[2017-01-17 20:50:26.612][INFO][main]:Before calling guaredMethod.
[2017-01-17 20:50:26.614][INFO][Thread-0]:waiting...
一起在保护中，xStateChanged调用改变保护对象的状态，不起作用！！！

**Comment by Viscent** [comment]
感谢您的反馈。这个不是问题。NestedMonitorLockoutExample这个类演示的就是“嵌套锁死”（Nested Monitor Lockout），即我们看到一直在“waiting...”的这个效果。后面我在代码中加个注释来说明这点的，因为光看代码不看书就会以为这是个代码错误（实际上是为展示代码错误而写的）。
